### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by faizync** [lohanidamodar/flutter_firestore_crud#1]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Faizan\AndroidStudioProjects\flutter_firestore_crud\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

**Comment by lohanidamodar** [comment]
First try `flutter clean` and to build again,

And you console must have more errors, please attach the screenshot as well. Also try to run with `flutter run --verbose` it will provide more output as where the error occurred.

**Comment by lohanidamodar** [comment]
Closed due to inactivity.
